### ISSUE TITLE
Option to enable/disable based on spec/equipped weapons

### ISSUE THREAD

**Issue by merijn** [hypernormalisation/SwedgeTimer#6]
While very helpful for fury DPS, I find the swing timer rather distracting when I'm tanking. At the moment I'm manually enabling/disabling the swing timers when I change specs, but it would be nice if there was an option to enable/disable based on which spec is active.

**Comment by merijn** [comment]
Related: https://www.wowace.com/projects/libdualspec-1-0

I might try and have a crack at adding support, but that will take some figuring out for me.

**Comment by hypernormalisation** [comment]
Agree that'd be a nice feature, I'll add it to the roadmap.

**Comment by hypernormalisation** [comment]
![image](https://github.com/hypernormalisation/SwedgeTimer/assets/52763122/c70332fe-93c5-43f3-93bd-d0c7f8106da5)

Implemented in 2.0.8, thanks for the feedback Merijn!
